version: "3.9"
services:
  application:
    image: lorenzomilicia/go-queue-server:main
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://db:5432/queueserver
      DB_USERNAME: queueserver
      DB_PASSWORD: queueserver
    command: 'go run .'
  db:
    image: "postgres"
    ports:
      - "50001:5432"
    environment:
      POSTGRES_DB: queueserver
      POSTGRES_USER: queueserver
      POSTGRES_PASSWORD: queueserver